version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.0
jobs:
    # The build job
    build:
        working_directory: ~/repo
        docker:
            - image: circleci/buildpack-deps:18.04-browsers
        steps:
          # Checkout the code from the branch into the working_directory
          - checkout
          - install_container_dependencies
          - run:
              name: Install dependencies
              command: bash -i -c 'npm ci'
          - run:
              name: Check dependencies
              command: bash -i -c 'npm ls'
          - run:
              name: Lint
              command: bash -i -c 'npm run lint'
          - run:
              name: Build
              command: bash -i -c 'npm run build.prod'
    deploy:
        working_directory: ~/repo
        docker:
            - image: circleci/python:2.7
        steps:
          - aws-s3/copy:
              from: dist
              to: 's3://overbeck.ui.builds'
              arguments: '--dryrun'
          
workflows:
  version: 2
  everything:
    jobs:
      - build
      - deploy:
          requires:
            - build
commands:
  install_container_dependencies:
    steps:
      - run:
          name: Install npm
          command: |
            wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
            bash -i -c 'nvm install'
